### ISSUE TITLE
where are those homework answers? how to run the devtool?

### ISSUE THREAD

**Issue by fcctrain** [alanarnholt/PASWR2#4]
i've downloaded all packages and havn't found any homework answers yet.
devtool link is not working.
could you please help us to handle this?

**Comment by alanarnholt** [comment]
Assuming you are asking for odd answers to the text Probability and Statistics with R, Second Edition,
the site http://alanarnholt.github.io/PASWR2E-Book/supplement.html has supplemental materials inclucing a pdf with odd answers.`devtools` is not a link but an R package.Try downloading the PASWR2 package from CRAN if you are not familiar with `devtools`.
