### ISSUE TITLE
Errant symbols in nsize() function

### ISSUE THREAD

**Issue by PeteArm** [alanarnholt/PASWR2#6]
I've been having some trouble with chapter8.R trying to create the pdf file through Rstudio. I keep getting the message that there is a keyboard character undefined. I had a look at the result tex file, and found the issue was with the result of the nsize function.

**Comment by PeteArm** [comment]
Comtinuing on, the result of using a call like nsize(b = .02, sigma = 0.1, conf.level = .95, type = "mu") should be the comment ## The required sample size (n) to estimate the population 
## mean with a 0.95 confidence interval so that the margin 
## of error is no more than 0.02 is 97. What I get instead is ## The required sample size (n) to estimate the population 
## mean with a 0.95 confidence interval so that the margin 
## of error is no more than 0.02 is 97 .

**Comment by alanarnholt** [comment]
Thanks for the issue.  Please explain more how you are using the function, what operating system you are using, and a reproducible example if possible.  From what you have provided, my "guess" is the issue may have something to do with your LaTeX installation...not the function.  Does the function run in your console?

**Comment by alanarnholt** [comment]
Please install the GitHub version of PASWR2 and the nsize() problem you described should be fixed.  If you notice the same problem in other functions, please let me know.
